// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Definisjon struct {
	ID         string `json:"id"`
	OppslagID  string `json:"oppslagId"`
	Prioritet  int    `json:"prioritet"`
	Definisjon string `json:"definisjon"`
	Opprettet  string `json:"opprettet"`
}

type Oppslag struct {
	ID           string        `json:"id"`
	Oppslag      string        `json:"oppslag"`
	Ledd         *string       `json:"ledd"`
	BoyTabell    *string       `json:"boyTabell"`
	Definisjoner []*Definisjon `json:"definisjoner"`
}
